/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CydwClock_1.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBMIDI_1.h"
#include "USBMIDI_1_audio.h"
#include "USBMIDI_1_cdc.h"
#include "USBMIDI_1_hid.h"
#include "USBMIDI_1_midi.h"
#include "USBMIDI_1_pvt.h"
#include "USBMIDI_1_cydmac.h"
#include "USBMIDI_1_msc.h"
#include "UART_1.h"
#include "Bootloadable_1.h"
#include "Bootl_aliases.h"
#include "Bootl.h"
#include "Status_Reg_1.h"
#include "LED_aliases.h"
#include "LED.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "Clock_4.h"
#include "I2COLED.h"
#include "I2COLED_PVT.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "RES_1_aliases.h"
#include "RES_1.h"
#include "USBMIDI_1_Dm_aliases.h"
#include "USBMIDI_1_Dm.h"
#include "USBMIDI_1_Dp_aliases.h"
#include "USBMIDI_1_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

